<a href="https://colab.research.google.com/github/Biswarys/Bank_Customer-Churn_Prediction-Using-ANN/blob/main/Bank_Customer_Churn_Prediction_by_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Bank Customer Churn Prediction by ANN

This project attempts to predict which customers will be likely to churn by Artificial Neural Network method.

In [1]:
# Import Necessary Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
tf.__version__

'2.15.0'

# Part 1 : Data Preprocessing

#### Importing the Dataset

In [3]:
dataset = pd.read_csv("/content/Churn_Modelling.csv")

In [4]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

Here Rownumber, CustomerID, Surname are not required. So we should exclude them for out model along with the dependent variable.


In [5]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [7]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [8]:
print(y)

[1 0 1 ... 1 1 0]


#### Encode Categorical Data

In [9]:
#Label encode the Gender Column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[: , 2] = le.fit_transform(X[: , 2])

In [10]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [11]:
#One Hot Encoding the Countries Column

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [12]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


#### Split the Dataset into Training and Test set

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

#### Feature Scaling

Feature Scaling is CUMPULSORY for Deep Learning

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Part 2 : Building the ANN

Initializing the ANN

In [15]:
ann = tf.keras.models.Sequential()

Add the Input Layer and the First Hidden Layer

In [16]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

Add the Second Hidden Layer

In [17]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

Add the Output Layer

In [18]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

# Part 3 : Training the ANN

#### Compling the ANN

In [27]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
#For Binary classification Loss function is binary_crossentropy and for non-binary its categorical_crossentropy, For regression its mean_squared_error

#### Training the ANN on the training set

In [20]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 2ms/step - loss: 0.5298 - accuracy: 0.7788
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4672 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4474 - accuracy: 0.7977
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4353 - accuracy: 0.8067
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4283 - accuracy: 0.8129
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4241 - accuracy: 0.8163
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4211 - accuracy: 0.8188
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4183 - accuracy: 0.8239
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4152 - accuracy: 0.8255
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4124 - accura

# Part 4 : Predict and Evaluate the Model

Predict the result of a single observation

Use ANN Model to predict whether a customers with below info will Churn or Not

Geography: France
Credit Score : 600
Gender : M
Age: 40
Tenure: 3 years
Balance - 60000
No of Products: 2
Credit Card : Y
Active Member: Y
Salary: 50000  

In [23]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))

1/1 [==============================] - 0s 34ms/step
[[0.02077322]]


20.77% chance of Customer Churn *italicized text*

In [24]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5 )

1/1 [==============================] - 0s 21ms/step
[[False]]


# Predict the Test Set Results

In [25]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

63/63 [==============================] - 0s 3ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


# Mark the Confusion Matrix

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1526   69]
 [ 206  199]]


0.8625